### ISSUE TITLE
listPlaylistsWithSong extension doesn't work

### ISSUE THREAD

**Issue by ianrispin** [huhridge/huh-spicetify-extensions#1]
Spotify version: v1.1.76.447.g11f432d8
Spicetify version: v2.8.4
OS: macOS Monterey 12.1

When I click list playlists with this song in the right-click menu, nothing happens in the app and I get this error in the console:
![listPlaylists-issue](https://user-images.githubusercontent.com/50210259/149644277-6e5bd4d7-9af4-45d1-bf7e-c031369d014e.png)
I have the [comfy](https://github.com/NYRI4/Comfy-spicetify) theme installed, along with the comfy.js extension, if that might be related.

**Comment by huhridge** [comment]
Updated the extension to skip empty playlists, which was the issue.
