### ISSUE TITLE
Lyrics 

### ISSUE THREAD

**Issue by Owsinay** [huhridge/huh-spicetify-extensions#10]
in the full display mode lyrics dont work, even if i restart spotify and change settings

**Comment by huhridge** [comment]
check this : https://canary.discord.com/channels/842219447716151306/957682140374511616/957888871704703008

**Comment by Owsinay** [comment]
this isnt working


pon., 4 kwi 2022 o 18:30 huhridge ***@***.***> napisał(a):

**Comment by xSharkTale** [comment]
Lyrics is not working. Please Fix this.

**Comment by ForlornWolf** [comment]
Fix: https://github.com/huhridge/huh-spicetify-extensions/issues/6

**Comment by noblereign** [comment]
> check this : https://canary.discord.com/channels/842219447716151306/957682140374511616/957888871704703008

what server is this supposed to be in?? can you please send a screenshot of the message

**Comment by huhridge** [comment]
> > check this : https://canary.discord.com/channels/842219447716151306/957682140374511616/957888871704703008
> 
> what server is this supposed to be in?? can you please send a screenshot of the message

it's the same as the comment above:

> Fix: #6
