### ISSUE TITLE
fullAppDisplayMod README missing

### ISSUE THREAD

**Issue by ZXSwire3** [huhridge/huh-spicetify-extensions#12]
The link the to the [fullAppDisplayMod README](https://github.com/huhridge/huh-spicetify-extensions/blob/main/fullAppDisplayMod/README.md) is dead. I was able to figure out what I needed to do to get it to work, but I just thought that I would mention it so that if someone else needs help setting it up, they would be able to figure it out.

**Comment by huhridge** [comment]
Thanks!
