### ISSUE TITLE
[Feature Request] Moving through song from progress bar

### ISSUE THREAD

**Issue by theerfan** [huhridge/huh-spicetify-extensions#13]
This issue is about the fullAppDisplayModified extension, whose progress bar, unlike the default Spotify progress bar, is unclickable and it's not possible to move through the different parts of the song by clicking on different parts of the progress bar.

I'd really appreciate it if you implemented this feature as well, thanks.

**Comment by huhridge** [comment]
I will try to implement it when I have some time, seems like it is a bit more complicated, than the volume bar, due to the progress bar being scaleable.

**Comment by huhridge** [comment]
I have added in the latest version, lemme know if there are any bugs!

If you're on an older version, then after you seek and pause it may move back to the original position, but the audio stays. It's a Spotify issue, can't do anything.

**Comment by theerfan** [comment]
Thank you so much man!
There's a little issue with the progress bar's movement when you click (the song seeks ok, but the progress bar looks like it moves to a random place before landing on the clicked zone), other than that, it's perfect!
[I think I'll try to see if I can work this one out and make a PR issue :D]

**Comment by huhridge** [comment]
I think that random position is unavoidable lol
