### ISSUE TITLE
[Feature Request] Add Volume control to FADM

### ISSUE THREAD

**Issue by nigelonius** [huhridge/huh-spicetify-extensions#14]
Please add volume control to Full App Display Modified extension. Please.

**Comment by huhridge** [comment]
I have added it, it is in testing phase right now.

A Sneak Peek:
![Screenshot 2022-04-28 at 16 59 10](https://user-images.githubusercontent.com/67046436/165742613-0bab8e29-5e09-4296-8f46-92fb2a1ec963.jpg)

**Comment by huhridge** [comment]
I have added it officially now! lemme know if there are any bugs!

**Comment by nigelonius** [comment]
Thank you so much. How do I view it? I have uninstalled and reinstalled the extension but I cant see it in the option menu.

**Comment by huhridge** [comment]
huh weird it should be there, "Enable volume bar"
![Screenshot 2022-05-03 at 11 13 33](https://user-images.githubusercontent.com/67046436/166409150-e469c548-4185-423f-9618-2c68a8a1fe9d.jpg)
Do you use marketplace? try from there maybe? or try downloading again?

**Comment by nigelonius** [comment]
That's odd, mine doesnt show that option:
![image](https://user-images.githubusercontent.com/87260000/166414203-f02be08a-8879-417b-978d-67c77ff304a7.png)
I used marketplace to install the extension and removed it and installed it again. I'm running Spotify for Windows
1.1.84.716.gc5f8b819

**Comment by huhridge** [comment]
Maybe a caching issue, no idea in the meantime you can manually install the extension if you want, sorry😓

**Comment by nigelonius** [comment]
what's the powershell command?

**Comment by huhridge** [comment]
> what's the powershell command?

Umm,so there isn't one, can you open the skipStats read me and install the extension that way, just replace `skipStats.js` with `fullAppDisplayMod.js`
