### ISSUE TITLE
[FullAppDisplay] The Button does not do anything.

### ISSUE THREAD

**Issue by MrTronMan** [huhridge/huh-spicetify-extensions#15]
the button in the top left is there but physically does not launch anything...I have tried reinstalling multiple times.

**Comment by huhridge** [comment]
Can you send more information? 
Spotify Version:
Spicetify Version:

Any errors in the console?
To check the console, run `spicetify enable-devtools` in the terminal, and press Ctrl+Shift+I/Cmd+Shift+I and check the console.

**Comment by D-Rekk** [comment]
It worked the first time, by the time I activated the "show Volume bar" option, the FullAppDisplay disappeared, now I can't active it anymore. Is there any chance I can reset the settings of the extension? I already uninstalled and reinstalled but I the problem persists

**Comment by huhridge** [comment]
can you send me the console ss, after clicking the button?
also you on discord? makes this easier

**Comment by D-Rekk** [comment]
D-Rek #8604 on Discord. I don't know exactly what to attach

**Comment by MrTronMan** [comment]
> It worked the first time, by the time I activated the "show Volume bar" option, the FullAppDisplay disappeared, now I can't active it anymore. Is there any chance I can reset the settings of the extension? I already uninstalled and reinstalled but I the problem persists

Exactly!

**Comment by huhridge** [comment]
Sorry, it's a problem with the new update (1.1.85) the volume function doesn't work, I would recommend you downgrade and wait until spicetify officially supports the new version

**Comment by MrTronMan** [comment]
Got it, thanks a lot
