### ISSUE TITLE
Lyrics Plus integration not working - [fullAppDisplayMod][BUG]

### ISSUE THREAD

**Issue by bdreaves04** [huhridge/huh-spicetify-extensions#17]
**Describe the bug**
Lyrics plus custom app integration of full app display modified not displaying lyrics even though the app is installed

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/63303767/170106407-affdbba6-9892-408c-9f24-df8ca826ed7c.png)

**Desktop (please complete the following information):**
 - OS: windows 11
 - Spotify Version: Spotify for Windows 1.1.84.716.gc5f8b819
 - Spicetify Version: v2.9.9 but also didn't work in v2.9.8

**Comment by huhridge** [comment]
When you re-enable the lyrics after disabling them, they go away and look like that. Can you try sending me any console errors, when you open full app display?

**Comment by bdreaves04** [comment]
![image](https://user-images.githubusercontent.com/63303767/170341531-4be84229-90e9-40f5-a2f6-b5324d857d4d.png)

these are the console errors that come up when I disable and reenable the lyrics plus integration, no additional errors are shown when opening the full app display extension

**Comment by huhridge** [comment]
I'll take a look when I get some time, sorry extremely busy with exams. 

Also don't have this problem on my machine, so very weird!

**Comment by Updog36** [comment]
I have the same issue as well

- OS: Windows 10
- Spotify Version: Spotify for Windows 1.1.91.824
- Spicetify Version: v2.11.1
- The latest commit of the .js (2 days ago)

The first two errors was me disabling the lyrics, the last one was me enabling them back again.
Afterwards, I skipped songs trying to make the lyrics "refresh", but nothing gets outputted to the console and the same issue as with OP persists.
![image](https://user-images.githubusercontent.com/94653983/183060126-36ffda8c-3b93-479c-acc7-e9833de8d231.png)

If it's of any help, I've [uploaded my config file](https://github.com/huhridge/huh-spicetify-extensions/files/9267878/config-xpui.-.Copy.txt)

**Comment by AbdulReja** [comment]
Try:
`spicetify config custom_apps lyrics-plus`, `spicetify apply` and try to enable lyrics again

**Comment by huhridge** [comment]
Does this still happen?

**Comment by Redhood27** [comment]
> 

yeah but i typed spicetify config custom_apps lyrics-plus and im good so thx

**Comment by huhridge** [comment]
Reopen if there is an issue.
