### ISSUE TITLE
[fullAppDisplayModified] [the lyrics feature dosent work]

### ISSUE THREAD

**Issue by YTisRuler2006** [huhridge/huh-spicetify-extensions#18]
**Describe the bug**
the lyrics feature dosent work

**To Reproduce**
install it from spicetify marketplace and try to use it

**Expected behavior**
the lyrics to show up

**Screenshots**
![image](https://user-images.githubusercontent.com/70239731/171512204-a8bfc3d1-e275-4bf5-ad91-7784a0c93dae.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Spotify Version: idk how to check
 - Spicetify Version: idk how to check

**Comment by huhridge** [comment]
Wrong repository lol
