### ISSUE TITLE
[fullAppDisplayMod.js] Add Next Up Toast!

### ISSUE THREAD

**Issue by karimawii** [huhridge/huh-spicetify-extensions#19]
Spotify's default full screen has this toast that appears in the last like 30 seconds of the current track that shows the next song in the queue and it stays there for the whole 30 seconds up until the next song plays. That would be useful especially in shuffle mode since you're kinda isolated from what's coming next when in full-screen mode and you'll never know what's the next song until it actually plays.
![image](https://user-images.githubusercontent.com/69881381/173108766-a0cb8f4b-23d9-4722-b6e9-3e43a60f71d9.png)

**Comment by huhridge** [comment]
If you hover over the next button, you should see the next song!

**Comment by karimawii** [comment]
oh, didn't know that, cool. Also great job overall!
