### ISSUE TITLE
Track names too large for small windows

### ISSUE THREAD

**Issue by Trinangle** [huhridge/huh-spicetify-extensions#2]
Hi there i love the extension its just what ive been looking for.

I have noticed that with track names with too long of a title the text causes any other optional elements of the display to not fit.
I think that just resizing the text based on the length of the track could maybe be an easy fix

Issue:
![image](https://user-images.githubusercontent.com/97986514/150011442-a337ca8d-1188-403c-ab76-ee136f56e569.png)

How it should be:
![image](https://user-images.githubusercontent.com/97986514/150011511-f94dd197-b6a4-4958-8d31-52f9571cf0fe.png)
but with smaller text

**Comment by Trinangle** [comment]
This only happens when Lyrics plus compatibility is enabled

**Comment by huhridge** [comment]
it doesn't look like that on my end,
![Screenshot 2022-01-19 at 10 19 46](https://user-images.githubusercontent.com/67046436/150066177-daf3b31a-130c-4a36-9acc-1784fc52b157.jpg)
but i'll look into it

**Comment by huhridge** [comment]
i'll look into it

**Comment by Trinangle** [comment]
It only happens when the window is small
