### ISSUE TITLE
[full App Display Modified] Volume bar not updating while changing volume

### ISSUE THREAD

**Issue by Tetrax-10** [huhridge/huh-spicetify-extensions#20]
I am using [Seek-Song](https://github.com/Tetrax-10/Spicetify-Extensions/tree/master/Seek-Song) Extension.
when I seek a song the progress bar updates correctly but the volume bar is not updating when I change volume.
The volume bar is not updating even using the stock `ctrl + up`

https://user-images.githubusercontent.com/75513645/173170805-47ee8a3e-a0d1-4f4f-9b7f-aa8a84caaca1.mp4

**Comment by huhridge** [comment]
That's my bad, thought there wasn't a way to change spotify volume without clicking, so it doesn't update, i'll add it in the next version
