### ISSUE TITLE
[fullAppDisplayMod.js] Detach From Spotify Option

### ISSUE THREAD

**Issue by karimawii** [huhridge/huh-spicetify-extensions#21]
If possible, add an option to detach the full display view to a separate window to be able to use Spotify normally while having the full display view on another screen for multi-screen users or even for single-screen users just alt-tabbing between Spotify and full display would be much easier than using `ESC` and click the full display icon again.

**Comment by huhridge** [comment]
I have looked into this, seems to be not possible atm, maybe i can find something later!
