### ISSUE TITLE
[Full App Display] Activation Button is Missing on Linux

### ISSUE THREAD

**Issue by The-L3mur** [huhridge/huh-spicetify-extensions#22]
**Describe the bug**
After installing the extension from the Spicetify Marketplace and restarting the app, the button does not appear.

**To Reproduce**
1. Install extension through the Marketplace
2. Relaunch Spotify
3. Notice button is missing

**Expected behavior**
The button would appear somewhere in the window, maybe next to the back/forward buttons.

**Console Errors**
None that were from this extension

**Screenshots**
(blanked out any personal info kind of things, but did not change any of the actual interface)
![bug_screenshot_redacted](https://user-images.githubusercontent.com/30356285/183271426-649c0fd7-ddfc-490a-9e62-a3dc6e627bcc.png)

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Spotify Version: 1.1.84.716.gc5f8b819
 - Spicetify Version: 2.11.1

**Additional context**
Using the GNOME Desktop Environment.

**Comment by huhridge** [comment]
Can you install any other extensions? I am not sure why this is happening, can you send me the console screenshots anyway? Maybe 2.11.1 is incompatible with 1.1.84, maybe an older version is better suited(2.8.4 iirc).

**Comment by ZXSwire3** [comment]
I'm having the same issue., but I'm on Windows 10. I tried reinstalling an older version of spicetify (2.8.4) but it won't show up either.

**Comment by Krishna-bansall** [comment]
I'm also having the same issue on Manjaro

**Comment by huhridge** [comment]
Does this still happen?

**Comment by The-L3mur** [comment]
It does not! All fixed now, thanks!
