### ISSUE TITLE
[fullAppDisplayMod.js] Static Background Color Option

### ISSUE THREAD

**Issue by karimawii** [huhridge/huh-spicetify-extensions#24]
Hey, so, the dynamic color change is very cool and I love it, but sometimes I just need a static color of my choice as the background, so maybe add it to this dropdown:

![image](https://user-images.githubusercontent.com/69881381/185498742-ee115c83-0369-4bab-b21b-1ff70650349e.png)

add "Static color" and if selected show an option below to add a HEX/RGB color code. Thanks!

**Comment by joejoe135791** [comment]
I was just going to suggest this, it would make chroma keying in obs a lot easier

**Comment by huhridge** [comment]
done!
