### ISSUE TITLE
[fullappDisplayModified][Lyrics dont showed up]

### ISSUE THREAD

**Issue by Danikkx** [huhridge/huh-spicetify-extensions#25]
**Describe the bug**
Nothing lyrics showed up until i play a song

**To Reproduce**

**Expected behavior**

**Console Errors**
To check the console, run `spicetify enable-devtools` in the terminal, and press <kbd>Ctrl</kbd>/<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> and check the console.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Spotify Version: 1.1.92.647
 - Spicetify Version: 2.12.0
![Screenshot (36)](https://user-images.githubusercontent.com/112271891/187041432-23facf77-cdd2-4d29-873c-28eeb5829327.png)

**Additional context**

**Comment by huhridge** [comment]
Does it not work at all, or after closing and opening, it works again?

**Comment by Danikkx** [comment]
Nope, If i close and opened it again, it will be the same problems

Pada tanggal Rab, 31 Agt 2022 18:49, huhridge ***@***.***>
menulis:

**Comment by huhridge** [comment]
Do you have lyrics-plus installed?

try `spicetify config custom_apps lyrics-plus`, `spicetify apply` and try again

**Comment by huhridge** [comment]
I'll close this for now, lemme know if there are any further developments.
