### ISSUE TITLE
List playlist with songs and playlist Intersection UI bug

### ISSUE THREAD

**Issue by Tetrax-10** [huhridge/huh-spicetify-extensions#29]
Spotify: `1.1.94.870.gf994cb0b`
Spicetify: `  2.13.1`
OS; `Win 11`

UI just overlaps
![image](https://user-images.githubusercontent.com/75513645/190886316-4a74c3a5-be7a-4e32-b74f-82370abd1839.png)
![image](https://user-images.githubusercontent.com/75513645/190886317-e199e7c6-afe4-441b-abd7-1906c2f0e054.png)

**Comment by huhridge** [comment]
Thanks for reporting! Lemme know if there are any further issues.
