### ISSUE TITLE
listPlaylistsWithSong.js not working here

### ISSUE THREAD

**Issue by luckybuzz** [huhridge/huh-spicetify-extensions#3]
hi there huhridge,

when i right-click songs, i see the option to "list playlists with this song" in the context menu, but clicking that does nothing.  i've tried for numerous songs, and tried right-clicking from within a playlist, an album, search results and my queue.

i'm really excited to use this feature, so i'll do anything i can to help you fix/test!  dropping a bunch of details below but let me know if i can provide any others  :)

Spotify version 1.1.77.643
Spicetify version 2.8.4
extensions activated: 
tweetMusic.js|playNext.js|genre.js|songstats.js|fullAlbumDate.js|fullAppDisplayMod.js|listPlaylistsWithSong.js
custom apps activated: new-releases|lyrics-plus|taste-analyser

**Comment by huhridge** [comment]
have you updated it? there was a commit 12 days ago, that solved something like this. 
Try updating if you haven't, if it doesn't work then, send me screenshot of the console in dev-tools
Enable dev tools by running, `spicetify enable-devtool`, and open console

**Comment by luckybuzz** [comment]
thanks for your reply.  yes, using the most recent version of the extension.

my console shows identical errors to the previous reported Issue, just with different line numbers in listPlaylistWithSong.js

![image](https://user-images.githubusercontent.com/16674992/151568006-d1b6b6f3-f80f-4b63-b70f-ec603e594f16.png)

**Comment by huhridge** [comment]
can you run this in console and paste the contents in a pastebin and send it here:
```javascript
userContents = await Spicetify.Platform.RootlistAPI.getContents()
copy(userContents)
```

**Comment by luckybuzz** [comment]
hello again!  i believe all the playlists i own or follow have an image.  even the ones without a custom image usually generate an image from the first 4 tracks' album art.

i have the console data you requested, however pastebin rejected it as it detected some potentially offensive content (???), so i am sending a zerobin link instead: https://zerobin.net/?c1ac378672180757#NItRYQa6Knm8SY3jsBDJiGGZFdBcT3nQ/xc87o3DcxU=

hope this helps!

**Comment by huhridge** [comment]
I made a temporary commit for now, which should work!
gonna look at this tomorrow

**Comment by huhridge** [comment]
![Screenshot 2022-01-29 at 10 35 15](https://user-images.githubusercontent.com/67046436/151648173-32830893-9cab-4718-867d-f15c94e1108b.jpg)

found the problem, this playlist has songs but doesn't have an image, which is weird because it definitely does,

![Screenshot 2022-01-29 at 10 51 34](https://user-images.githubusercontent.com/67046436/151648621-9dbe7a0c-d492-4153-b004-be2a2911005f.jpg)

**Comment by luckybuzz** [comment]
wow, good catch!  i guess since that playlist is made up of songs no longer on spotify, the cover art must not be registering correctly.  i'll throw a .png on there as playlist art.  thanks for all your help and detective work!

**Comment by huhridge** [comment]
I feel like the temp commit may just become permanent, to solve these weird edge cases.
It is working with the commit right?

**Comment by luckybuzz** [comment]
yes indeed, been putting it to good use this evening. :)

**Comment by huhridge** [comment]
imma close this then, thanks for reporting
