### ISSUE TITLE
full app dispaly modified][I enable lyrics plus integration, but there is no lyrics]

### ISSUE THREAD

**Issue by Leslie-Ngai** [huhridge/huh-spicetify-extensions#30]
**Describe the bug**
I enable lyrics plus integration, but there is no lyrics

**To Reproduce**
I downloaded full app display in marketplace on spotify,and I clicked the full app display on the top left corner on spotify .then I saw the album picture,singer name,but I didn't see any lyrics even I had enabled the lyrics plus integration. And spotify has lyrics of these songs.
**Expected behavior**
I wanna see the lyrics of the full display modified
**Screenshots**
![no lyrics](https://user-images.githubusercontent.com/114425264/192332189-a3bda7fe-d1d6-45b4-a971-d46eee181f1b.jpg)
![I had enabled the lyrics plus integration ](https://user-images.githubusercontent.com/114425264/192332225-3c5bf693-320e-4746-a006-cb688f625742.jpg)
![And spotify has lyrics of these songs.](https://user-images.githubusercontent.com/114425264/192333086-5309df24-0c05-4de2-a32f-6d99e420f5e1.jpg)

 - Spotify Version:1.1.94.872
 - I hope u can help me figure it  out,Thax

**Comment by huhridge** [comment]
Do you have lyrics-plus installed?

try spicetify config custom_apps lyrics-plus, spicetify apply and try again

**Comment by Leslie-Ngai** [comment]
> Do you have lyrics-plus installed?
> 
> try `spicetify config custom_apps lyrics-plus` , `spicetify apply` and try again

Toady I found that the I can not see the full app display midified bar on the spotify,but I actully download it![IMG_20220927_090025.jpg](https://user-images.githubusercontent.com/114425264/192407212-d2fc9146-be19-4d96-8095-fbda998775ab.jpg)

**Comment by huhridge** [comment]
This happens sometimes with marketplace, the best thing is to relaunch or refresh if you have enabled devtools

**Comment by Leslie-Ngai** [comment]
> This happens sometimes with marketplace, the best thing is to relaunch or refresh if you have enabled devtools

Thax. I think it was spotify update (new ui) that caused it. I uninstalled the new version of spotify and installed the old one.then this problem was solved.
