### ISSUE TITLE
[fullAppDisplay][Lyrics don't show up]

### ISSUE THREAD

**Issue by InCrafter** [huhridge/huh-spicetify-extensions#31]
---
name: Lyrics don't show up.
about: Lyrics missing in fullscreen mode.
title: "[fullAppDisplay][Lyrics don't show up]"
labels: bug
assignees: huhridge

---

**Describe the bug**
When I toggle the option to show lyrics, the Album Cover and text move but the lyric space stays empty. 

**To Reproduce**
Toggle Full Display Mode.
Toggle Lyric Option.

**Expected behavior**
I expect the lyrics to show up next to the album cover.

**Console Errors**
![image](https://user-images.githubusercontent.com/26893126/195197231-b6c6001d-8d72-4a84-a0b5-492e3d6b9e6b.png)
[xpui.app.spotify.com-1665522070725.log](https://github.com/huhridge/huh-spicetify-extensions/files/9759751/xpui.app.spotify.com-1665522070725.log)

**Screenshots**
![image](https://user-images.githubusercontent.com/26893126/195197352-5f0d7a56-7592-4412-9789-380e37108614.png)

**Desktop**
 - OS: Windows 11
 - Spotify Version: 2.14.0
 - Spicetify Version: 1.1.95.893.g6cf4d40c

**Comment by huhridge** [comment]
Do you have lyrics-plus installed?

try spicetify config custom_apps lyrics-plus , spicetify apply and try again

**Comment by InCrafter** [comment]
works now. thanks
