### ISSUE TITLE
[SkipStats][BUG]Always zoomed in after clicking button

### ISSUE THREAD

**Issue by Nova1ite** [huhridge/huh-spicetify-extensions#34]
**Describe the bug**
SkipStats always zoomed in after clicking the "See Skip Stats" button in context menu

**To Reproduce**
Steps to reproduce the behavior: Clicking "See Skip Stats" in context menu and automatically zooms in

**Expected behavior**
Should have the default zoom after clicking the button

**Console Errors**
To check the console, run `spicetify enable-devtools` in the terminal, and press <kbd>Ctrl</kbd>/<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> and check the console.

**Screenshots**
[
![Untitled5](https://user-images.githubusercontent.com/115776661/206354716-2d078d90-6a19-437c-ade8-54a70adb68dd.png)
![Untitled6](https://user-images.githubusercontent.com/115776661/206354721-4da3c2f7-1a54-4676-ad69-af30e99b6758.png)
](url)

**Desktop (please complete the following information):**
 - OS: Windows 11 64-bit (22h2)
 - Spotify Version: 1.2.0.1165.gabf054ab
 - Spicetify Version: v2.14.3

**Additional context**

**Comment by huhridge** [comment]
Not an issue with the extension, it's the same for every modal in spicetify which is large.
