### ISSUE TITLE
[Full App Display modified][Lyrics not working in Full Display Mode]

### ISSUE THREAD

**Issue by Overrevvv** [huhridge/huh-spicetify-extensions#35]
Lyrics don't work in Full Display Mode and the Display button sometimes disappears. 

**To Reproduce**

Step 1: Open any song in Full Display Mode and exit.
Step 2: Click on the Lyrics button.
Step 3: Full Display Button Will disappear after these steps.

**Expected behavior**
I expected to display Lyrics in Full Display mode

**Console Errors**
To check the console, run `spicetify enable-devtools` in the terminal, and press <kbd>Ctrl</kbd>/<kbd>Cmd</kbd>+<kbd>Shift</kbd>+<kbd>i</kbd> and check the console.

Button Disappeared after is tried to open Lyrics 
![image](https://user-images.githubusercontent.com/98686837/206859654-e327f98c-b00e-44ba-9511-ba5a6642d0f8.png)

 - OS: Windows 10 21H2
 - Spotify Version: Spotify for Windows 1.1.93.896.g3ae3b4f3
 - Spicetify Version: 2.13.0

**Comment by huhridge** [comment]
Add some information.

**Comment by Overrevvv** [comment]
Sorry about that I accidently sent it without much information. I tried to use this extension and found it don't work with lyrics and when I use lyrics and try to go back to Full Display Mode, Display Button always disappears.

**Comment by huhridge** [comment]
Huh, this is a very weird one, are you on discord?

**Comment by Overrevvv** [comment]
Yes, I have discord, it was my bad it works now, I updated Spicetify and Spotify and installed lyrics-plus.
