### ISSUE TITLE
Full App Display - Progress bar is not centered when using a verical monitor

### ISSUE THREAD

**Issue by tsadnoula** [huhridge/huh-spicetify-extensions#36]
Hello,

When using the vertical mode, but not the vertical monitor mode the progress bar is not centered, leaning bit to the left. See more from the pictures attached. Hope this can get fixed soon.
![Huomautus 2022-12-28 053046](https://user-images.githubusercontent.com/114976930/209752877-6645b669-148d-490f-b033-ea6863ee8f8b.png)

**Comment by Nikkoro** [comment]
It is related to hardcoded `min-width:400px` value at `#fad-status`. You can remove  or lower `min-width:400px`. You can also remove `min-width:56px` from  `#fad-elapsed`. It's not a perfect solution, but if you don't use extra controls, it will look fine.
