### ISSUE TITLE
[Full App Disaply][High cpu usage when enable progress bar]

### ISSUE THREAD

**Issue by vathanac** [huhridge/huh-spicetify-extensions#38]
**Screenshots**
![Spotify_7nMah915RW](https://user-images.githubusercontent.com/87689818/210358824-f553b992-5753-44b2-b7a5-fbf36076a85f.gif)

**Desktop (please complete the following information):**
 - OS: Windows 
 - Spotify Version: 1.2.O.1165.gabf054ab
 - Spicetify Version: 2.16

**Comment by huhridge** [comment]
Can't do anything about it sorry
