### ISSUE TITLE
[Display full Album date][BUG]

### ISSUE THREAD

**Issue by zero-mindset** [huhridge/huh-spicetify-extensions#41]
Hi, the extension appears to be showing one day behind.

There are a ton of albums on Spotify without proper release date metadata that simply show Jan, 1 ____ for the release date when they don’t have the exact date info for it, but know the year. I’ve noticed that the extension, at least for me, is always showing one day behind the actual release date. So, in these unknown date cases, the app thinks the release date is Dec 31 ____ and thus showing the incorrect release year (ie 2004 instead of 2005).

(https://imgur.com/a/n9OGOph)

 - OS: MacOS Ventura 13.0.1
 - Spotify Version: Spotify for macOS (Intel)
1.2.3.1115.gd61a8f5c
- Spicetify v2.16.0

**Comment by huhridge** [comment]
That's weird, it's showing the correct date for me

**Comment by huhridge** [comment]
I think I've figured it out, the gets converted using your locale, so if your timezone is behind utc, it gets shifted a day prior.

**Comment by zero-mindset** [comment]
Interesting. Okay, yeah I’m in the States so I’m definitely behind UTC.
Don’t suppose there’s any way to modify that behavior in the extension?

**Comment by huhridge** [comment]
I'll see if I can do something.

**Comment by zero-mindset** [comment]
Okay. I appreciate you looking into it regardless. Thanks.

**Comment by huhridge** [comment]
Can you try the latest version of the extension?

**Comment by zero-mindset** [comment]
It appears to still be doing the same thing

**Comment by huhridge** [comment]
Did you try it through marketplace or manually? Because marketplace takes a while to update the caches

**Comment by zero-mindset** [comment]
Through marketplace. It shows that it was updated today (29th) for what
it’s worth

**Comment by zero-mindset** [comment]
Hi. It seems to be working now. Just tired pulling from the Marketplace
again. I appreciate the fix!

**Comment by zero-mindset** [comment]
Very odd actually. It’s working for some albums now and not for others.
That’s really strange
