### ISSUE TITLE
Full App Display[BUG]

### ISSUE THREAD

**Issue by NHellForce** [huhridge/huh-spicetify-extensions#42]
in display setting it says Unable to fin Lyrics Plus

 - OS:Windows 10 Pro
 - Spotify Version:1.2.3.1115
 - Spicetify Version: 2.16.0

Other setting fully works but I can't activate lyrics on full display mod
![image](https://user-images.githubusercontent.com/123460999/214267154-7a5f5294-e500-4e34-b4b9-4acfad24c948.png)

**Comment by huhridge** [comment]
run `spicetify config custom_apps lyrics-plus` and `spicetify apply`
