### ISSUE TITLE
Full App Display lyrics not showing

### ISSUE THREAD

**Issue by Xaypanya** [huhridge/huh-spicetify-extensions#43]
**Describe the bug**
Lyrics not showing when enter full screen and tv mode even the song has lyrics

**Screenshots**
when not enter full screen:
![image](https://user-images.githubusercontent.com/67275080/215191052-5741bad7-543e-41e3-bb67-ccaedfe5a09b.png)
when enter full screen:
![image](https://user-images.githubusercontent.com/67275080/215191139-2ecd82eb-e6e4-416c-8c6f-c546d1870812.png)

 - OS: Windows 10
 - Spotify Version:
 - Spicetify Version:

**Comment by huhridge** [comment]
This is not my extension
