### ISSUE TITLE
[fullAppDisplayModified][BUG]

### ISSUE THREAD

**Issue by Boring-student** [huhridge/huh-spicetify-extensions#44]
**Describe the bug**
Interface is broken but it's still clickable with couple button.

**To Reproduce**
(optional) Freshy install the plugin.
1. Start the music.
2. Click at the fullAppDisplay button.

**Expected behavior**
It should work as intend as the picture show in the extension readme.

**Console Errors**

`fullAppDisplayMod.js:1078 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'isLocalTrack')`
    `at FAD.fetchInfo (fullAppDisplayMod.js:1078:31)`
    `at FAD.componentDidMount (fullAppDisplayMod.js:1343:18)`
    `at ps (vendor~xpui.js:29:5590903)`
    `at Ll (vendor~xpui.js:29:5607709)`
    `at t.unstable_runWithPriority (vendor~xpui.js:29:5821875)`
    `at Ho (vendor~xpui.js:29:5549898)`
    `at Cl (vendor~xpui.js:29:5604448)`
    `at hl (vendor~xpui.js:29:5600559)`
    `at cl (vendor~xpui.js:29:5597690)`
    `at Zl (vendor~xpui.js:29:5613775)`

**Screenshots**
![image](https://user-images.githubusercontent.com/74827801/219082122-1446a5b4-f430-4532-b83a-d949b85ff5be.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 21H1 x86
 - Spotify Version: 1.2.4.912
 - Spicetify Version: 2.16.0

**Comment by huhridge** [comment]
update your spicetify
