### ISSUE TITLE
Lyrics text color - white color option

### ISSUE THREAD

**Issue by tuvsheeo** [huhridge/huh-spicetify-extensions#46]
The lyrics in full screen follows the color of the current theme, and mostly there is very little contrast. It would be great if we had the option to change the color of the text to white (or a color of our choice) just like the song details.

If there is a simple way to change the script and modify it yourself, instructions would be much appreciated.

![image](https://user-images.githubusercontent.com/106656011/219700022-13605577-4dac-4aee-acad-bb479be22545.png)

**Comment by huhridge** [comment]
it should be working now!
