### ISSUE TITLE
How do I know what delay to set it to goToSong

### ISSUE THREAD

**Issue by YourLocalAlle** [huhridge/huh-spicetify-extensions#47]
GoToSong tells me to adjust the delay in order for it to work but I don't know what delay to set it to

**Comment by FroggyRaven** [comment]
same issue

**Comment by huhridge** [comment]
keep increasing it until it works :)

**Comment by Qwertyzk69** [comment]
is gotosong dead now cuz no matter what delay i use it keeps throwing the error
