### ISSUE TITLE
Fullscreen not displaying properly on a vertical monitor.

### ISSUE THREAD

**Issue by BogdanValentin** [huhridge/huh-spicetify-extensions#5]
![Screenshot 2022-02-13 151040](https://user-images.githubusercontent.com/63101897/153754752-2c713577-6e27-4cc0-9b8a-e451d785c911.png)
While using the extension on a 1680x1050 monitor in portrait mode the upper region is not working properly.

**Comment by BogdanValentin** [comment]
![Screenshot 2022-02-13 151504](https://user-images.githubusercontent.com/63101897/153754865-1bb16cce-32b0-4598-bb5d-91864f298408.png)
If I first enter full screen mode on my main monitor and then i drag the app on the second one the black bar disappears but the text and artwork are not centered.

**Comment by huhridge** [comment]
I know why the text is off centre, I'll fix it in a bit, don't know about the other one, are you on discord by any chance?

**Comment by BogdanValentin** [comment]
> I know why the text is off centre, I'll fix it in a bit, don't know about the other one, are you on discord by any chance?

No, but I can help you with more photos or screen recordings if you want.

**Comment by huhridge** [comment]
I fixed the canvas thing, try it now, I'll fix the aligning thing in a bit

**Comment by huhridge** [comment]
would it be fine if I added a mode for the vertical monitor where, the lyrics and album art are stacked instead of being side-by-side?

**Comment by BogdanValentin** [comment]
> would it be fine if I added a mode for the vertical monitor where, the lyrics and album art are stacked instead of being side-by-side?

Why not, the more modes available the better.
Also thanks for the fix, the blur now scales to the whole screen and the background artwork no longer stretches.

**Comment by huhridge** [comment]
try the latest version, the mode only appears if you have lyrics enabled and the window is actually vertical. lemme know if there are any problems

**Comment by BogdanValentin** [comment]
It works well, thank you very much for your help.
I might tweak it myself by raising the lyrics, but other than that, no problems.

**Comment by huhridge** [comment]
increase this to increase the height of the lyrics
![Screenshot 2022-02-20 at 13 33 11](https://user-images.githubusercontent.com/67046436/154833927-cce14529-b3d6-4c60-988d-8e7b7bb2ce7e.jpg)
