### ISSUE TITLE
[Full App Display][background color choice "prominent" broken]

### ISSUE THREAD

**Issue by cougarten** [huhridge/huh-spicetify-extensions#50]
**Describe the bug**
If you set your prominent there will be console errors and the background will be transparent.
All other colors work fine, even the other dynamic ones like "vibrant".

**To Reproduce**
- open full app display
- right click for settings
- set background to "colorful background"
- set Color Choice to "prominent"

**Expected behavior**
Should give me a nice full color background.

**Console Errors**
On enabling prominent:
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/7131556/11c51dd8-ac64-4ee3-80f1-4f6eac3f0a7a)

On skipping to next track:
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/7131556/a654872c-fa92-4621-83b1-3a6c041c8543)

**Screenshots**
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/7131556/67479678-232a-4aff-bd80-5bb518f9c431)

**Desktop (please complete the following information):**
 - OS: win
 - Spotify Version: ~latest I think
 - Spicetify Version: ~latest I think

**Additional context**
It used to work a few weeks ago.

**Comment by huhridge** [comment]
this option seemed to have been removed from the api itself
