### ISSUE TITLE
[REQ][Full App Display] Hide lyrics control buttons

### ISSUE THREAD

**Issue by younyokel** [huhridge/huh-spicetify-extensions#57]
Need an option to hide these lyrics control buttons for Full App Display
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/53343081/08f99623-40d9-4e6e-acde-e49c5be2188b)

**Comment by TheAdeenZ16** [comment]
Still nothing?

**Comment by huhridge** [comment]
done!
