### ISSUE TITLE
[Full App Display][BUG]

### ISSUE THREAD

**Issue by khwnnnn** [huhridge/huh-spicetify-extensions#58]
Whyyyyy like this
![Screenshot (206)](https://github.com/huhridge/huh-spicetify-extensions/assets/137049801/3cc94cd9-a4ff-410d-9b8b-59c2dbac4fe1)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Spotify Version: 1.2.13.661
 - Spicetify Version: v2.20.1

**Comment by PerryDH** [comment]
I had the same problem, that's how I solved it, I hope it helps you, sorry for my English
![Spotify_fhkfTk3SlL](https://github.com/huhridge/huh-spicetify-extensions/assets/48692767/7952c407-7314-4c5a-9e86-2faaac870bfe)
![Spotify_UvnvxOqY87](https://github.com/huhridge/huh-spicetify-extensions/assets/48692767/64d46866-94af-4d3a-9ee7-15461d554424)
Choose left
![Spotify_9aUonWndbM](https://github.com/huhridge/huh-spicetify-extensions/assets/48692767/dfefec38-b08f-45ae-b697-2ca0ccc32221)
![Spotify_nwiD3hCqLc](https://github.com/huhridge/huh-spicetify-extensions/assets/48692767/d170b954-6d41-43b9-a8f6-d6c6b379d0db)

**Comment by NarQq** [comment]
same issue + the little white bar bottom of the screen flashes whenever the lyrics switch
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/91109302/e453b1a2-6f7c-4212-8cf6-26ec489a05a6)

**Comment by TheAdeenZ16** [comment]
When will this be fixed?

**Comment by mccalltristan** [comment]
The fix works kind of, but still some of the lyrics are off the screen. This only started happening a few weeks ago.
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/134766063/97116b5a-9713-411b-96b1-c04292b16a3d)

**Comment by ohitstom** [comment]
for anyone still having issues, until huhridge can merge my PR, just use the extension from my branch.

**Comment by mccalltristan** [comment]
> for anyone still having issues, until huhridge can merge my PR, just use the extension from my branch.

Doesn't fix it
