### ISSUE TITLE
[Display full Album date][BUG]

### ISSUE THREAD

**Issue by thegoldknight** [huhridge/huh-spicetify-extensions#60]
**Describe the bug**
The extension does not show full album date, only year.

**Console Errors**
<img width="1440" alt="image" src="https://github.com/huhridge/huh-spicetify-extensions/assets/135397968/bdf45fee-070c-4992-b3b7-847356a99c92">

**Desktop (please complete the following information):**
 - OS: macOS
 - Spotify Version: 1.12.13
 - Spicetify Version: 2.20.1

**Comment by 5aad666** [comment]
I am also facing the same issue 

Win 11
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/108563567/6eaff91f-173e-4c1c-80a1-0952c0aef968)

**Comment by huhridge** [comment]
should be fixed now!

**Comment by stebo02** [comment]
I'm facing this issue again...

I'm on an older version of spotify if that helps...

Spotify for Windows (32 bit)
1.2.17.834.g26ee1129
Spicetify v2.36.11
