### ISSUE TITLE
[Full App Display ][Lyrics placement]

### ISSUE THREAD

**Issue by RodrigoRLuis** [huhridge/huh-spicetify-extensions#65]
It's a visual bug with the lyrics, they show up off to the right side of the screen, almost completely off the screen. My screen resolution is 1080p and the scale is on 100%.

**Screenshots**
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/114607044/e6ed5ac4-590e-4bcf-a83a-893aae16d8e2)

**Desktop (please complete the following information):**
 - OS: Win10
 - Spotify Version: 1.2.14.1149.ga3ae422d
 - Spicetify Version: v2.20.2

**Comment by CrZen** [comment]
Yeah, can confirm. This is also happening to me

**Comment by DevilKun-7** [comment]
Same issue for me :(

**Comment by iannnnnn0** [comment]
![Lyrics-Plus Bug](https://github.com/huhridge/huh-spicetify-extensions/assets/77594819/6d8c7760-e58e-4419-9c51-03c22a585034)
Same here, but my resolution is 2560 x 1440

**Comment by DTrombett** [comment]
Can reproduce
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/73136330/71ec26a0-3acf-4c14-85a8-ab9ff57e0bc6)

**Comment by DTrombett** [comment]
As a temporary fix you can add the following CSS to your snippets:
```css
#fad-lyrics-plus-container {
    position: relative;
}
```

**Comment by gamerdada** [comment]
> As a temporary fix you can add the following CSS to your snippets:
> 
> ```css
> #fad-lyrics-plus-container {
>     position: relative;
> }
> ```

This is already in file like this :

#fad-lyrics-plus-container {
    position: relative;
    width: 50vw;
}


I have tried removing "width" and even tried to "align" but invain this Temporary fix is not working

**Comment by ohitstom** [comment]
> > As a temporary fix you can add the following CSS to your snippets:
> > ```css
> > #fad-lyrics-plus-container {
> >     position: relative;
> > }
> > ```
> 
> This is already in file like this :
> 
> #fad-lyrics-plus-container {     position: relative; width: 50vw; }
> 
> I have tried removing "width" and even tried to "align" but invain this Temporary fix is not working

![image](https://github.com/huhridge/huh-spicetify-extensions/assets/22730962/b9a49381-1620-49dc-9968-beaeb3a23fe9)
this is because i had formatted it incorrectly as i hadnt realized this was code injected into head as a <script> tag, my latest pr will fix this, just add a new snippet and !Important it with marketplace for now.

**Comment by gamerdada** [comment]
> > > As a temporary fix you can add the following CSS to your snippets:
> > > ```css
> > > #fad-lyrics-plus-container {
> > >     position: relative;
> > > }
> > > ```
> > 
> > 
> > This is already in file like this :
> > #fad-lyrics-plus-container {     position: relative; width: 50vw; }
> > I have tried removing "width" and even tried to "align" but invain this Temporary fix is not working
> 
> ![image](https://user-images.githubusercontent.com/22730962/250168847-b9a49381-1620-49dc-9968-beaeb3a23fe9.png) this is because i hadnt formatted it incorrectly as i hadnt realized this was code injected into head as a <script> tag, my latest pr will fix this, just add a new snippet and !Important it with marketplace for now.

Thanks, it resolved the issue

**Comment by Seudonym** [comment]
do you have to make it !important. Adding right: 0; is simpler and better long term no?
