### ISSUE TITLE
[Full app display modified][the lyrics are in the wrong position]

### ISSUE THREAD

**Issue by DeathLuck578** [huhridge/huh-spicetify-extensions#68]
**Describe the bug**
the lyrics are too far-right so it's barely readable 

**To Reproduce**
enter full-screen mode and turn on the lyrics

**Expected behavior**
![Screenshot 2023-07-04 171102](https://github.com/huhridge/huh-spicetify-extensions/assets/137679577/a7542edf-daa7-47c3-9110-b41d8f00c285)

**Screenshots**
![Screenshot 2023-07-04 170740](https://github.com/huhridge/huh-spicetify-extensions/assets/137679577/74a10729-7dd5-49c5-aca5-bfe1282a01e4)

**Desktop (please complete the following information):**
Spotify for Windows (32 bit)
1.2.14.1149.ga3ae422d
Spicetify v2.20.3

**Comment by TwinTusks** [comment]
This issue had been documented, see #65
