### ISSUE TITLE
[Full App Display Modified][Vertical Monitor Mode Breaks 'lyrics-plus' integration]

### ISSUE THREAD

**Issue by maybMedia** [huhridge/huh-spicetify-extensions#69]
**Describe the bug**
Enabling vertical monitor mode causes the lyrics from 'lyrics-plus' integration to render either at the very bottom of the window or off the window completely.

**To Reproduce**
Enable vertical monitor mode and 'lyrics-plus' integration.

**Expected behavior**
I expect the lyrics to render below the album cover and song info with a small gap. As it did in previous versions.

**Console Errors**
There are many errors logged but none relating to this extension. 
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/61731103/402ecc0a-8f9b-4f1c-940a-f6d09fd165e5)

**Screenshots**
In vertical monitor mode:
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/61731103/834392d0-2ce9-4814-957e-b49ace26de34)
Not in vertical monitor mode:
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/61731103/1bad81fe-43e5-4051-aefb-5bbbc5c08b23)

**Desktop:**
 - OS: Windows 10
 - Spotify Version: Spotify for Windows(64 bit) - 1.2.16.947.gcfbaa410
 - Spicetify Version: v2.21.0

**Additional context**
- Changing vertical mode(not vertical monitor mode) does not fix the issue.
- Issue started after most recent update.
- Updated marketplace

**Comment by huhridge** [comment]
should be fixed now!
