### ISSUE TITLE
FullAppDisplayModified | Colourful background option now returns black

### ISSUE THREAD

**Issue by RJTomk** [huhridge/huh-spicetify-extensions#7]
As the title states, the colourful background option now only gives a black background, regardless of colour choice. F6 colour display window shows all colours as black as well.

![Colour picker window](https://user-images.githubusercontent.com/32545783/159109109-df57a206-a225-467a-a362-38544f32ddb4.png)
.

**Comment by huhridge** [comment]
Sorry, I know, it's an issue with the new update. I already made an [issue](https://github.com/spicetify/spicetify-cli/issues/1537) on spicetify-cli GitHub. Hope someone can fix it

**Comment by RJTomk** [comment]
It's [dribbblish-dynamic](https://github.com/JulienMaille/dribbblish-dynamic-theme).
