### ISSUE TITLE
[DisplayUi][BUG]

### ISSUE THREAD

**Issue by MmGaboimM** [huhridge/huh-spicetify-extensions#75]
**Screenshots**
![image](https://github.com/huhridge/huh-spicetify-extensions/assets/96992621/2cd62388-26e0-4640-8dd9-a0781874943c)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro
 - Spotify Version:Spotify for Windows (64 bit)
1.2.19.941.gbf202593
 - Spicetify Version:v2.22.1

**Comment by huhridge** [comment]
not my extension
