### ISSUE TITLE
Full App Display not showing up properly

### ISSUE THREAD

**Issue by Pastelblue1** [huhridge/huh-spicetify-extensions#81]
Hey, 

When I click on the ''Full App Display'' button, it does not open with the album cover in the background it just shows the main page with the song in the middle but the album cover is invisible. Also, when the song changes it does not update the album cover in the background.

Here is an example:

![Screenshot 2023-11-07 161608](https://github.com/huhridge/huh-spicetify-extensions/assets/101512163/439c07cc-8e7e-4902-859e-494d7c05103e)

I'm not sure what I need to do to fix this so any help will be appreciated!

Thanks

**Comment by jabuxas** [comment]
same happened to me after installing lyrics-plus and running `spicetify restore backup apply`, was working before.

**Comment by huhridge** [comment]
it should be fixed now!

**Comment by jabuxas** [comment]
indeed
