### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by 57ryk3r** [huhridge/huh-spicetify-extensions#9]
After I click 'List playlists with this song', I have to immediately right click and click 'List playlists with this song' again or else it'll only take  me to the album page

**Comment by 57ryk3r** [comment]
To further expand,it does work infrequently but most of the time, I have to do the workaround and sometimes the page will go blank after I do the workaround. I've recorded the bug for you: https://gofile.io/d/k6JavR

Discord is SC | StrykerRed#1980 if you need it

**Comment by huhridge** [comment]
Join the server: https://discord.gg/J8UvZTDz, the problem is maybe your internet? Idk, join discord, then i can diagnose the issue better
